Description: Candidates Portal - Frontend

Resources:
  # S3
  FrontendBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: boucekm-candidates-portal-frontend
      WebsiteConfiguration:
        IndexDocument: index.html
