Description: Web React App - Frontend

Resources:
  # S3
  FrontendBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: boucekm-web-react-app
      WebsiteConfiguration:
        IndexDocument: index.html
