service: candidates-portal-backend

package:
  exclude:
    - coverage/**
    - jest.config.js
    - README.md
    - yarn.lock
    - .dynamodb/**
    - test/**
    - seed/**
    - handler.test.js

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  versionFunctions: false
  logRetentionInDays: 30
  iamRoleStatements:
   - Effect: Allow
     Action:
      - dynamodb:GetItem
      - dynamodb:UpdateItem
     Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.JOBS_TABLE}"
   - Effect: Allow
     Action:
      - dynamodb:GetItem
      - dynamodb:UpdateItem
     Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PROFILES_TABLE}"
  environment:
    JOBS_TABLE: candidates-portal-jobs-${self:provider.stage}
    PROFILES_TABLE: candidates-portal-profiles-${self:provider.stage}
    FRONTEND_URL: http://realchangers-candidates-portal-${self:provider.stage}-frontend.s3-website-eu-west-1.amazonaws.com

functions:
  graphql:
    handler: graphql.handler
    events:
      - http:
          path: query
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:222582984103:userpool/eu-west-1_hVc5GjCPH
          cors:
            origin: ${self:provider.environment.FRONTEND_URL}
            maxAge: 86400
      - http:
          path: query
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:222582984103:userpool/eu-west-1_hVc5GjCPH
          cors:
            origin: ${self:provider.environment.FRONTEND_URL}
            maxAge: 86400
  jobPublisher:
    handler: jobPublisher.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - UsersTable
              - StreamArn

resources:
  Description: Candidates Portal - Backend
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: cognitoID
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: cognitoID
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.JOBS_TABLE}
    ProfilesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES # NEW_IMAGE | OLD_IMAGE | NEW_AND_OLD_IMAGES | KEYS_ONLY
        TableName: ${self:provider.environment.PROFILES_TABLE}

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-offline-dynamodb-stream
  - serverless-offline # must be last plugin

custom:
  dynamodb:
    host: localhost
    port: 8000
    start:
      migrate: true
      seed: true
      inMemory: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.JOBS_TABLE}
            sources: [./seed/jobOffers.json]
          - table: ${self:provider.environment.PROFILES_TABLE}
            sources: [./seed/profiles.json]
  dynamodbStream:
    host: localhost
    port: 8000
    pollForever: true
    streams:
      - table: ${self:provider.environment.PROFILES_TABLE}
        functions:
          - jobPublisher
  serverless-offline:
    port: 8080
