service: web-react-app-backend

package:
  exclude:
    - coverage/**
    - jest.config.js
    - README.md
    - yarn.lock
    - .dynamodb/**
    - test/**

custom:
  dynamodb:
    start:
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}
            sources: [./test/testData.json]
  serverless-offline:
    port: 8080

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
   - Effect: Allow
     Action:
      - dynamodb:GetItem
      - dynamodb:UpdateItem
     Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: post
      - http:
          path: query
          method: get

plugins:
  - serverless-dynamodb-local
  - serverless-offline # must be last plugin

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
