service: web-react-app-backend

package:
  exclude:
    - coverage/**
    - jest.config.js
    - README.md
    - yarn.lock
    - .dynamodb/**

custom:
  dynamodb:
    start:
      migrate: true
  serverless-offline:
    port: 8080

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
   - Effect: Allow
     Action:
      - dynamodb:GetItem
      - dynamodb:UpdateItem
     Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  hello:
    handler: handler.query
    events:
      - http:
          path: query
          method: get

plugins:
  - serverless-dynamodb-local
  - serverless-offline # must be last plugin

resources:
  Resources:
    NicknamesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: firstName
            AttributeType: S
        KeySchema:
          - AttributeName: firstName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
