service: candidates-portal-backend

package:
  exclude:
    - coverage/**
    - jest.config.js
    - README.md
    - yarn.lock
    - .dynamodb/**
    - test/**
    - seed/**
    - handler.test.js

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  versionFunctions: false
  logRetentionInDays: 30
  iamRoleStatements:
   - Effect: Allow
     Action:
      - dynamodb:GetItem
      - dynamodb:UpdateItem
     Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  environment:
    DYNAMODB_TABLE: candidates-portal-${self:provider.stage}
    FRONTEND_URL: http://realchangers-candidates-portal-${self:provider.stage}-frontend.s3-website.eu-west-1.amazonaws.com

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: post
          cors:
            origin: ${self:provider.environment.FRONTEND_URL}
            maxAge: 86400
      - http:
          path: query
          method: get
          cors:
            origin: ${self:provider.environment.FRONTEND_URL}
            maxAge: 86400

resources:
  Description: Candidates Portal - Backend
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

plugins:
  - serverless-dynamodb-local
  - serverless-offline # must be last plugin

custom:
  dynamodb:
    start:
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}
            sources: [./seed/users.json]
  serverless-offline:
    port: 8080
