service: web-react-app

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.query
    events:
      - http:
          path: query
          method: get

plugins:
  - serverless-offline
